# Generated by Django 5.2 on 2025-05-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bazzar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=50)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('emp_contact', models.IntegerField()),
                ('emp_dob', models.DateField()),
                ('emp_state', models.CharField(max_length=50)),
                ('emp_gender', models.CharField(max_length=50)),
                ('emp_password', models.CharField(max_length=15)),
                ('emp_profile', models.ImageField(null=True, upload_to='profile_pics/')),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=50)),
                ('stu_email', models.EmailField(max_length=254, unique=True)),
                ('stu_query', models.CharField(max_length=50)),
            ],
        ),
    ]
