# Generated by Django 5.2 on 2025-05-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='stu_email',
            field=models.EmailField(max_length=254),
        ),
    ]
