# Generated by Django 5.2 on 2025-05-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_query_stu_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='stu_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
