# Generated by Django 5.2 on 2025-05-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_query_stu_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='Querys',
        ),
    ]
