# Generated by Django 5.2.1 on 2025-05-09 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='passwprd',
        ),
    ]
