# Generated by Django 5.2 on 2025-04-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('discrip', models.CharField(max_length=300)),
                ('phone', models.IntegerField(max_length=50)),
                ('dob', models.DateField(max_length=50)),
                ('subscribe', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image/')),
                ('resume', models.FileField(upload_to='file/')),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
