# Generated by Django 5.2.1 on 2025-05-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='username',
            field=models.CharField(default='Ano', max_length=50),
        ),
    ]
