# Generated by Django 5.2 on 2025-05-06 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vicals',
            name='Fuel_name',
            field=models.ManyToManyField(related_name='vicals', to='myapp.fuel'),
        ),
    ]
