# Generated by Django 5.2 on 2025-04-25 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Baseinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('baseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.baseinfo')),
                ('salary', models.IntegerField(max_length=60)),
                ('age', models.IntegerField(max_length=60)),
            ],
            bases=('myapp.baseinfo',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('baseinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='myapp.baseinfo')),
                ('rollno', models.IntegerField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
            bases=('myapp.baseinfo',),
        ),
    ]
