# Generated by Django 5.2 on 2025-04-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('elec', 'Electronics'), ('furn', 'Furniture')], max_length=4)),
            ],
        ),
    ]
